### ISSUE TITLE
Getting access to this repo

### ISSUE THREAD

**Issue by mlautman** [ros-gbp/panda_moveit_config-release#1]
@rhaschke I would like to release the newest melodic changes but I don't think I have access to do so. Would it be possible to get access to release panda_moveit_config and moveit_tutorials since I tend to be the most active maintainer on those repos?

**Comment by rhaschke** [comment]
Sorry, but I just accidentally found this email.
Please send me a direct email, if you don't get a response within a few days.

I created a team @ros-gbp/moveit-maintainers, which can be reused for all release repos of MoveIt.
Unfortunately, github doesn't allow me to add you to this team, as you are not member of the ros-gbp organization. I added you as collaborator though.
